# https://swanlab.cn
# https://docs.swanlab.cn/guide_cloud/integration/integration-pytorch-lightning.html

swanlab:
  _target_: swanlab.integration.pytorch_lightning.SwanLabLogger
  project: "research-project"
  experiment_name: null
